# **Python Fundamentals**
**What is Python?**

Per [wikipedia](https://en.wikipedia.org/wiki/Python_(programming_language))

> Python is an interpreted, high-level, general-purpose programming language. Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.

**Why learn it?**

Python has a wide range of use cases to include **data analytics**. As analytics and data science have become more prominent in the past decade, it has quickly become an industry standard. The tools we will be using in this class are all built off of Python.  

**What do I need to know about python?**

Python's syntax is **indentation-based**.  This means that white space matters when you are writing Python code.  As a result, Python code becomes formatted neatly and is easier to read.  Don't worry if this doesn't mean anything to you right now, we will get into this shortly.  



---



# **Variables and Data Types**

Variables are containers for storing values.  
You assign values to variables by using =

In [ ]:
x = 3

In [ ]:
print(x)

3


You can overwrite the value of an existing variable by assigning a new value to it in the same way.

In [ ]:
x = 5

In [ ]:
print(x)

5


There are many different types of values that can be stored in variables.  
Common data types include:
* Integer
* Float
* String
* Boolean 
* List
* Dictionary 



## Integers and Floats
`int` and `float` respectively are types of numeric values.



In [ ]:
# Integers and Floats
radius = 2  # This is an integer
pi = 3.14   # This is a float

# You can mix integers and floats in calculations
area_of_circle = pi * radius * radius
print(area_of_circle)
type(area_of_circle)

12.56


float

## Strings
`str` are "strings" of text characters

In [ ]:
# String
# A string of text wrapped in single, double, or triple quotes

hello = 'Hello' # Single Quotes
world = "World"  # Double Quotes
# Triple Quotes for multi-line strings 
preamble = """
We the People of the United States, 
in Order to form a more perfect Union, 
establish Justice, ensure domestic Tranquility, 
provide for the common defence, 
promote the general Welfare, 
and secure the Blessings of Liberty to ourselves and our Posterity, 
do ordain and establish this Constitution for the United States of America.
"""

## String concatenation
Strings can be "added" i.e. concatenated together with other strings

In [ ]:
greeting = hello + ' ' + world
print(greeting)

Hello World


However, strings cannot be concatenated to non-strings

In [ ]:
love_amount = 3000  # int
i_love_python = "I love Python " # str
# print(i_love_python + love_amount) # error

love_amount = str(love_amount)
print(type(a))
print(type(love_amount))

<class 'str'>
<class 'str'>


But, we can cast (i.e. convert) variables from one type to another by wrapping the variable name in str() or int() or float() etc.

In [ ]:
love_amount_str = str(love_amount)  # Casts from int to str
print(i_love_python + love_amount_str)

I love Python 3000


## Boolean
`bool` is a true or false value

In [ ]:
t = True
f = False

# We can combine boolean values (or expressions that evaluate to boolean values)
# using logical operators (e.g. and, or, not)

print("True and False: ", t and f)
print("True or False: ", t or f)
print("Not False: ", not f)

True and False:  False
True or False:  True
Not False:  True


## Lists
`list` are a data structure consisting of a list of ordered, comma-separated values contained within brackets.
They can contain different data types.

In [ ]:
my_empty_list = []
my_list = [1,2,3,4,5,6,7,8,9]
my_str_list = ["a","b","c"]
my_mixed_list = ["a", 1, 2.5, True]

Lists are helpful to organize data and process them in order.

Data in a list can be accessed using the index (i.e. order number) of the desired element in the list. 

*   The first element in the list has an index of 0
*   The last element in the list has an index of -1
*   A "slice" of the list can be grabbed by specifying the first (inclusive) and last (exclusive) indices





In [ ]:
my_list[0] # the first element of the list

1

In [ ]:
my_str_list[2] # the third element of the list

'c'

In [ ]:
my_list[-1] # the last element of the list

9

In [ ]:
my_list[0:3] # a list containing only the first three items of the list

[1, 2, 3]

The length of a list can be calculated using `len()`

In [ ]:
len(my_list)

9

New items can be added to a list by using `append()`

Lists can also be added to each other to concatenate them.

In [ ]:
my_list.append(10)
print(my_list) # [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# We can also add (concatenate) lists
a = [1,2,3]
b = [4,5,6]
c = a + b
print(c) # [1, 2, 3, 4, 5, 6]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6]


## Dictionary

A **dictionary** is a key/value map.  That is, **keys** can be used to store and look up **values**.

In [ ]:
empty_dictionary = {}
student_record = {
    "name": "Harry Potter",
    "school": "Hogwarts",
    "house": "Gryffindor",
    "year": 1,
    "age": 11,
    "friends": ["Hermione Granger", "Ron Weasley"],
    "speaks_parseltongue": True
}

In [ ]:
# Values can be accessed using the key name
# The key name is wrapped in square brackets or get()
print(student_record["age"]) # 11
print(student_record.get("friends")) # ['Hermione Granger', 'Ron Weasley']

11
['Hermione Granger', 'Ron Weasley']


In [ ]:
# New key/value pairs can always be added to the dictionary
student_record["enemies"] = ["Draco Malfoy"]
print(student_record)

{'name': 'Harry Potter', 'school': 'Hogwarts', 'house': 'Gryffindor', 'year': 1, 'age': 11, 'friends': ['Hermione Granger', 'Ron Weasley'], 'speaks_parseltongue': True, 'enemies': ['Draco Malfoy']}


In [ ]:
# Existing values can be updated with new values
student_record["age"] = 12
print(student_record)

{'name': 'Harry Potter', 'school': 'Hogwarts', 'house': 'Gryffindor', 'year': 1, 'age': 12, 'friends': ['Hermione Granger', 'Ron Weasley'], 'speaks_parseltongue': True, 'enemies': ['Draco Malfoy']}


# **Python Operators**
## Arithmetic Operators
**\+** : Addition

**\-** : Subtraction

**\*** : Multiplication

**/** : Division

**%** : Modulo

****** : Exponent

## Comparison Operators
**==** : equal to

**\>=** : greater than or equal to

**\>**  : greater than

**<=** : less than or equal to

**<**  : less than

**!=** : not equal to

## Assignment Operators

**\=** : Assigns a value to a variable

**+=** : Adds the value and assigns it to the variable

## Logical Operators
x **and** y : True if x and y are both True

x **or** y : True if at least one of x or y are True

**not** x : True if x is False, False if x is True

In [ ]:
5 == 5

True

In [ ]:
1 == 2

False

In [ ]:
"dog" != "cat"

True

In [ ]:
1000 > 100

True

In [ ]:
7 % 4

3

In [ ]:
2 ** 4

16

In [ ]:
x = 5
x += 2 # equivalent to x = x + 2
print(x)

7


In [ ]:
university = "USF"
course = "MSDS 596"

print(university == "USF" and course == "MSDS 595")

False


## **If statements**

We can add if statements to our code, so that code only runs if a certain condition is met.

*Note: This is the first time we're seeing the indentation referenced earlier.  All code to be executed when the `if` condition is met should be at the same level of indentation.*

In [ ]:
# Let's go back to our Harry Potter student record
print(student_record)

{'name': 'Harry Potter', 'school': 'Hogwarts', 'house': 'Gryffindor', 'year': 1, 'age': 12, 'friends': ['Hermione Granger', 'Ron Weasley'], 'speaks_parseltongue': True, 'enemies': ['Draco Malfoy']}


In [ ]:
if student_record["school"] == "Hogwart":
    print(student_record["name"] + "'s headmaster is Albus Dumbledore")
    print("1")
    print("2")
print("3")

3


In [ ]:
# Only 3rd years and above are allowed to go to Hogsmeade. 
# Let's check this and print whether Harry is allowed to go

if student_record["year"] >= 3:
    print(student_record["name"] + " is permitted to go to Hogsmeade")
elif student_record["year"] >= 0 and student_record["year"] <= 2:
    print(student_record["name"] + " is NOT permitted to go to Hogsmeade")
else:
    print("Invalid student year")

Harry Potter is NOT permitted to go to Hogsmeade


## **Loops**

Loops allow you to iterate over a block of code.

See the different types of loops and use cases below.

## **`for` loops**

Iterates one item at a time through a sequence of items, allowing you to execute code on each item.  This is useful for processing data records, where you want to act on every record in some pre-determined way.


In [ ]:
# Let's look at an example of a simple for loop
names = ["Harry", "Ron", "Hermione", "Draco"]
for x in names:
    print(x)

Harry
Ron
Hermione
Draco


In [ ]:
# Here's another example, where we iterate through a list of items, look up its price, and update a running total

# total_cost will hold the running total. It is initalized to $0.
total_cost = 0
# price_catalog is a dictionary mapping items to prices
price_catalog = {
    "book": 20,
    "notebook": 5,
    "pencil": 1,
    "eraser": 0.25
}
# items_in_cart is a list of items we will be purchasing
items_in_cart = ["book", "notebook", "notebook", "pencil"]

for item in items_in_cart:
    print(item + " costs $" + str(price_catalog[item]))
    total_cost += price_catalog[item] # += means take the current value in the variable and add the new value to it

print("The total cost is $" + str(total_cost))

book costs $20
notebook costs $5
notebook costs $5
pencil costs $1
The total cost is $31


## **`while` loops**

Continue to loop through the code until the provided test expression is no longer true.  Be careful as you can have infinite loops if the test expression never evaluates to false.

In [ ]:
# Here is a while loop example

num_loops = 3
while num_loops > 0:
    print(num_loops)
    num_loops -= 1 # subtract 1 from num_loops every loop

3
2
1


## **Functions**

A function is a block of code that performs a specific action. Functions generally take an input and return an output.  Using functions is good coding practice, as it allows you to break otherwise large, unwieldy blocks of code into smaller, modular pieces that are easier to read/understand and are also reusable.

In [ ]:
# An example of a function
# This statement defines the function.
# The syntax is def my_function_name(some,input,variables):
# A value can be returned using "return"
def add_two_numbers(a, b):
    return a + b

# Now that the function is defined, we can call it.
print(add_two_numbers(student_record["age"], 5))

17


In [ ]:
# Another example of a function
def get_average(list_of_numbers):
    list_length = len(list_of_numbers)
    total = 0
    for number in list_of_numbers:
        total += number
    return total/list_length

some_numbers = [1,2,3,4,5,6]
print(get_average(some_numbers))

3.5


# Numpy

Numpy is a Python **library** focused on mathematical/scientific computing.

*What is a Python library?*

In simple terms, a **library** can be thought of as a collection of pre-written code that is usually centered around some common theme/function.  We can leverage this code, which has usually been thoroughly reviewed/maintained, in our own code so that we don't have to reinvent the wheel to perform common tasks.

*What does numpy do?*

Numpy provides a framework for n-dimensional arrays and mathematical functions to operate on these arrays.  This is broadly applicable to many fields, but is also especially useful in data analysis.  In fact, the core data analysis library that we will be using in this class **Pandas** is built off of the Numpy library.

Let's learn some of the basic features of Numpy.

Whenever we want to use code from a library, we need to **import** that library.

In [ ]:
import numpy as np

The core data structure provided by numpy is the **array**.  An **array** is similar to the **list** that comes natively with Python, but there are a few key differences.

*   More efficient calculations
*   Comes with plethora of built-in mathematical operations on arrays
*   Homogenous (all elements of the array have to be the same data type)



In [ ]:
student_ages = np.array([23, 26, 24, 24, 22, 31, 30, 27, 21, 22, 25, 25, 25, 34])

Now that we have loaded the data into a Numpy array, we can easily obtain common descriptive statistics using built-in methods.

Average (Mean) age

In [ ]:
np.mean(student_ages)

25.642857142857142

Maximum age

In [ ]:
np.max(student_ages)

34

Minimum age

In [ ]:
np.min(student_ages)

21

Median age

In [ ]:
np.median(student_ages)

25.0

## Element-wise arithmetic on arrays



In [ ]:
a = np.array([10,9,8])
b = np.array([2,2,1])
subtract = a - b
add = a + b
multiply = a * b
divide = a / b
print(subtract)
print(add)
print(multiply)
print(divide)

[8 7 7]
[12 11  9]
[20 18  8]
[5.  4.5 8. ]


# 2-Dimensional Arrays

One key feature of **Numpy** is its ability to work with n-dimensional arrays.  Let's work with a 2 dimensional array in the following example.  

In [ ]:
array_2d = np.array(
    [
     [1,2,3],
     [4,5,6],
     [7,8,9]
    ]
)

In [ ]:
np.sum(array_2d)  # This will sum all elements in the 2d array:  1+2+3+4+5+6+7+8+9

45

Use the `axis` argument to specify column or row specific calculations

`axis = 0` is a column aggregation

`axis = 1` is a row aggregation

In [ ]:
np.sum(array_2d, axis=0) # This will sum all elements for each column: [1+4+7, 2+5+8, 3+6+9]

array([12, 15, 18])

In [ ]:
np.sum(array_2d, axis=1) # This will sum all elements for each row: [1+2+3, 4+5+6, 7+8+9]

array([ 6, 15, 24])